# Generated by Django 4.0.3 on 2022-03-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField(verbose_name='Текст сообщения')),
                ('for_sending', models.CharField(choices=[('faculty', 'Факультет'), ('group', 'Группа'), ('all', 'Все')], max_length=10, verbose_name='Для кого отрпавлять уведомление')),
            ],
        ),
    ]
