# Generated by Django 3.2.13 on 2022-04-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField(verbose_name='Текст сообщения')),
                ('is_all_sending', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отправить для всех')),
                ('faculty_sending', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculties.faculty', verbose_name='Для какого факультета отправить уведомление')),
                ('group_sending', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group', verbose_name='Для какой группы отправить уведомление')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
