# Generated by Django 4.0.3 on 2022-03-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
        ('groups', '0002_alter_group_options_group_faculty_group_group_name'),
        ('messages_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='for_sending',
        ),
        migrations.AddField(
            model_name='message',
            name='faculty_sending',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculties.faculty', verbose_name='Для какого факультета отправить уведомление'),
        ),
        migrations.AddField(
            model_name='message',
            name='group_sending',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group', verbose_name='Для какой группы отправить уведомление'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_all_sending',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отправить для всех'),
        ),
    ]
