# Generated by Django 3.2.13 on 2022-04-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teachers', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Ваше сообщение для студентов')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Рассылка для преподавателя',
                'verbose_name_plural': 'Рассылка',
            },
        ),
    ]
