# Generated by Django 3.2.13 on 2022-04-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_messageteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageteacher',
            name='message',
            field=models.TextField(help_text='Вы можете отослать сообщение для какой-то конкретной группы. ВНИМАНИЕ! При сохранении рассылки отправится сообщение всем студентам', verbose_name='Ваше сообщение для студентов'),
        ),
    ]
