# Generated by Django 4.0.3 on 2022-03-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decan',
            options={'verbose_name': 'Декан', 'verbose_name_plural': 'Деканы'},
        ),
    ]
