# Generated by Django 4.0.3 on 2022-03-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
        ('decans', '0004_alter_decan_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='decan',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculties.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='decan',
            name='password',
            field=models.CharField(max_length=255, unique=True, verbose_name='Пароль'),
        ),
    ]
