# Generated by Django 4.0.3 on 2022-04-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decans', '0005_decan_faculty_alter_decan_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='decan',
            name='chat_id',
            field=models.CharField(max_length=255, null=True, verbose_name='chat_id'),
        ),
    ]
