# Generated by Django 4.0.3 on 2022-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chat_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Чат айди'),
        ),
    ]
