# Generated by Django 3.2.13 on 2022-04-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleForStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], max_length=255, verbose_name='День недели')),
                ('text_schedule', models.TextField(verbose_name='Текст расписания')),
                ('order', models.CharField(choices=[('denominator', 'Знаменатель'), ('numerator', 'Числитель')], max_length=255, verbose_name='Числитель/Знаменатель')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Рассписание для студента',
                'verbose_name_plural': 'Рассписание для студента',
            },
        ),
    ]
